// Code generated by "stringer -type=EvalType eval_type.go"; DO NOT EDIT

package stop

import "fmt"

const (
	_EvalType_name_0 = "TUnsupported"
	_EvalType_name_1 = "TString"
	_EvalType_name_2 = "TList"
	_EvalType_name_3 = "TMap"
	_EvalType_name_4 = "TBool"
)

var (
	_EvalType_index_0 = [...]uint8{0, 12}
	_EvalType_index_1 = [...]uint8{0, 7}
	_EvalType_index_2 = [...]uint8{0, 5}
	_EvalType_index_3 = [...]uint8{0, 4}
	_EvalType_index_4 = [...]uint8{0, 5}
)

func (i EvalType) String() string {
	switch {
	case i == 0:
		return _EvalType_name_0
	case i == 2:
		return _EvalType_name_1
	case i == 4:
		return _EvalType_name_2
	case i == 8:
		return _EvalType_name_3
	case i == 16:
		return _EvalType_name_4
	default:
		return fmt.Sprintf("EvalType(%d)", i)
	}
}
