// Code generated by "stringer -type=Type"; DO NOT EDIT

package ast

import "fmt"

const (
	_Type_name_0 = "TUnsupported"
	_Type_name_1 = "TAny"
	_Type_name_2 = "TString"
	_Type_name_3 = "TInt"
	_Type_name_4 = "TFloat"
	_Type_name_5 = "TList"
	_Type_name_6 = "TMap"
	_Type_name_7 = "TBool"
)

var (
	_Type_index_0 = [...]uint8{0, 12}
	_Type_index_1 = [...]uint8{0, 4}
	_Type_index_2 = [...]uint8{0, 7}
	_Type_index_3 = [...]uint8{0, 4}
	_Type_index_4 = [...]uint8{0, 6}
	_Type_index_5 = [...]uint8{0, 5}
	_Type_index_6 = [...]uint8{0, 4}
	_Type_index_7 = [...]uint8{0, 5}
)

func (i Type) String() string {
	switch {
	case i == 0:
		return _Type_name_0
	case i == 2:
		return _Type_name_1
	case i == 4:
		return _Type_name_2
	case i == 8:
		return _Type_name_3
	case i == 16:
		return _Type_name_4
	case i == 32:
		return _Type_name_5
	case i == 64:
		return _Type_name_6
	case i == 128:
		return _Type_name_7
	default:
		return fmt.Sprintf("Type(%d)", i)
	}
}
